# Generated by Django 5.2.17 on 2026-09-24 21:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('builds', '0001_initial'),
        ('catalog', '0005_market_stats'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('username', models.CharField(blank=True, max_length=64)),
                ('language', models.CharField(choices=[('uk', 'Українська'), ('en', 'English')], default='uk', max_length=2)),
                ('enabled', models.BooleanField(default=True, help_text='Send price alerts.')),
                ('quiet_hours', models.BooleanField(default=True, help_text='Hold alerts between 22:00 and 08:00 (Kyiv time).')),
                ('link_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('token_created_at', models.DateTimeField(blank=True, null=True)),
                ('linked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_price', models.DecimalField(blank=True, decimal_places=2, help_text='USD. Alert once the price reaches it (optional).', max_digits=12, null=True)),
                ('threshold_percent', models.PositiveSmallIntegerField(default=5, help_text='Alert when the price moves this much, either way.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('baseline_price', models.DecimalField(decimal_places=2, help_text='USD. Price when the watch was created or last alerted; changes count from it.', max_digits=12)),
                ('last_notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('build', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watches', to='builds.build')),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watches', to='catalog.component')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('component__isnull', False), ('build__isnull', True)), models.Q(('component__isnull', True), ('build__isnull', False)), _connector='OR'), name='watch_exactly_one_target'), models.UniqueConstraint(condition=models.Q(('component__isnull', False)), fields=('user', 'component'), name='watch_unique_component'), models.UniqueConstraint(condition=models.Q(('build__isnull', False)), fields=('user', 'build'), name='watch_unique_build')],
            },
        ),
    ]
