/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/advisor/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Recommend a complete, compatible build for a budget and use case.
         *
         *     Logged-in users only and rate limited: each call may cost LLM tokens.
         */
        post: operations["advisor_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["auth_me_retrieve"];
        put: operations["auth_me_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["auth_me_partial_update"];
        trace?: never;
    };
    "/api/auth/register/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_register_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/token/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description JWT login, rate limited per IP against password guessing. */
        post: operations["auth_token_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/token/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a refresh type JSON web token and returns an access type JSON web
         *     token if the refresh token is valid.
         */
        post: operations["auth_token_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/builds/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["builds_list"];
        put?: never;
        post: operations["builds_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/builds/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["builds_retrieve"];
        put: operations["builds_update"];
        post?: never;
        delete: operations["builds_destroy"];
        options?: never;
        head?: never;
        patch: operations["builds_partial_update"];
        trace?: never;
    };
    "/api/builds/{id}/clone/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Copy a visible build (e.g. someone's public build) into your own builds. */
        post: operations["builds_clone_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/builds/{id}/comments/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List build comments */
        get: operations["builds_comments_list"];
        put?: never;
        /** Comment on a build */
        post: operations["builds_comments_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/builds/{id}/compatibility/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["builds_compatibility_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["categories_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories/{slug}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["categories_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/comments/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["comments_retrieve"];
        put: operations["comments_update"];
        post?: never;
        delete: operations["comments_destroy"];
        options?: never;
        head?: never;
        patch: operations["comments_partial_update"];
        trace?: never;
    };
    "/api/compatibility/check/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Check an unsaved set of components. Used by the configurator for live feedback. */
        post: operations["compatibility_check_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/components/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["components_list"];
        put?: never;
        post: operations["components_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/components/{slug}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["components_retrieve"];
        put: operations["components_update"];
        post?: never;
        delete: operations["components_destroy"];
        options?: never;
        head?: never;
        patch: operations["components_partial_update"];
        trace?: never;
    };
    "/api/components/{slug}/listings/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Staff: attach a product page URL. It is fetched right away, so the
         *     response already contains the title, price and photos found there.
         */
        post: operations["components_listings_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/components/{slug}/price-history/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Daily price points, oldest first: typical (median) price and the day's range. */
        get: operations["components_price_history_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exchange-rates/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["exchange_rates_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exchange-rates/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["exchange_rates_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exchange-rates/latest/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["exchange_rates_latest_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/manufacturers/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["manufacturers_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/manufacturers/{slug}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["manufacturers_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["orders_list"];
        put?: never;
        post: operations["orders_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["orders_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{id}/advance/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Staff only: move the order along (paid → shipped → delivered). */
        post: operations["orders_advance_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{id}/cancel/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["orders_cancel_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{id}/pay/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["orders_pay_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/categories/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["stats_categories_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/cheapest-build/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The cheapest public build that contains the given GPU. */
        get: operations["stats_cheapest_build_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/popular-components/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["stats_popular_components_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/price-position/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Where each component sits on the price ladder of its category. */
        get: operations["stats_price_position_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/top-per-category/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Top-N most used components *within each category* — a window function.
         *
         *     ``RANK() OVER (PARTITION BY category ORDER BY build_count DESC)`` and then a
         *     filter on the window result (supported since Django 4.2, compiled into a
         *     subquery because SQL does not allow WHERE on window functions directly).
         */
        get: operations["stats_top_per_category_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/telegram/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Connection of the account to the Telegram bot. */
        get: operations["telegram_retrieve"];
        put?: never;
        post?: never;
        /** @description Disconnect the chat (the watches stay). */
        delete: operations["telegram_destroy"];
        options?: never;
        head?: never;
        /** @description Connection of the account to the Telegram bot. */
        patch: operations["telegram_partial_update"];
        trace?: never;
    };
    "/api/telegram/link/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Issue a one-time ``t.me/<bot>?start=<code>`` link (valid for 30 minutes). */
        post: operations["telegram_link_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watches/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The user's own price watches. Filter with ``?component=<id>`` or ``?build=<id>``. */
        get: operations["watches_list"];
        put?: never;
        /** @description The user's own price watches. Filter with ``?component=<id>`` or ``?build=<id>``. */
        post: operations["watches_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watches/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The user's own price watches. Filter with ``?component=<id>`` or ``?build=<id>``. */
        get: operations["watches_retrieve"];
        put?: never;
        post?: never;
        /** @description The user's own price watches. Filter with ``?component=<id>`` or ``?build=<id>``. */
        delete: operations["watches_destroy"];
        options?: never;
        head?: never;
        /** @description The user's own price watches. Filter with ``?component=<id>`` or ``?build=<id>``. */
        patch: operations["watches_partial_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description * `en` - en
         *     * `uk` - uk
         * @enum {string}
         */
        AdvisorLanguageEnum: "en" | "uk";
        AdvisorRequest: {
            /**
             * Format: decimal
             * @description Amount in `currency`.
             */
            budget: string;
            /**
             * @description UAH budgets are converted at the latest NBU rate; the catalog plans in USD.
             *
             *     * `USD` - USD
             *     * `UAH` - UAH
             * @default USD
             */
            currency: components["schemas"]["CurrencyEnum"];
            use_case: components["schemas"]["UseCaseEnum"];
            /** @default  */
            preferences: string;
            /**
             * @description Language of the summary and notes.
             *
             *     * `en` - en
             *     * `uk` - uk
             * @default en
             */
            language: components["schemas"]["AdvisorLanguageEnum"];
        };
        AdvisorResponse: {
            source: components["schemas"]["SourceEnum"];
            model: string;
            summary: string;
            notes: string[];
            components: components["schemas"]["ComponentBrief"][];
            /** Format: decimal */
            total_price: string;
            /**
             * Format: decimal
             * @description USD
             */
            budget: string;
            /**
             * Format: decimal
             * @description The budget as entered, in `budget_currency`.
             */
            budget_amount: string;
            budget_currency: components["schemas"]["CurrencyEnum"];
            compatibility: components["schemas"]["CompatibilityReport"];
        };
        /**
         * @description * `uk` - Українська
         *     * `en` - English
         * @enum {string}
         */
        AlertLanguageEnum: "uk" | "en";
        BuildDetail: {
            readonly id: number;
            name: string;
            description?: string;
            readonly owner: string;
            is_public?: boolean;
            readonly items: components["schemas"]["BuildItem"][];
            /** Format: decimal */
            readonly total_price: string;
            readonly compatibility: components["schemas"]["CompatibilityReport"];
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        BuildItem: {
            readonly id: number;
            readonly component: components["schemas"]["ComponentBrief"];
            quantity?: number;
            /** Format: decimal */
            readonly line_total: string;
        };
        BuildItemWriteRequest: {
            component: number;
            /** @default 1 */
            quantity: number;
        };
        BuildList: {
            readonly id: number;
            name: string;
            description?: string;
            readonly owner: string;
            is_public?: boolean;
            /** Format: decimal */
            readonly total_price: string;
            readonly parts_count: number;
            readonly comments_count: number;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /**
         * @description Create/update a build together with its component list.
         *
         *     Validation is layered on purpose:
         *     * field level  – each item references an active component, quantity 1..8;
         *     * ``validate_items`` – no duplicate components in one request;
         *     * ``validate`` – cross-field domain rules via the compatibility engine.
         *       This is the place for them: they depend on *all* items at once, which
         *       no single field validator can see;
         *     * database – unique (build, component) and the quantity range are also
         *       constraints, so a bug in this serializer cannot corrupt data.
         */
        BuildWriteRequest: {
            name: string;
            description?: string;
            is_public?: boolean;
            items?: components["schemas"]["BuildItemWriteRequest"][];
        };
        Category: {
            readonly id: number;
            kind: components["schemas"]["CategoryKindEnum"];
            name: string;
            slug: string;
            position?: number;
        };
        /**
         * @description * `cpu` - Processor
         *     * `motherboard` - Motherboard
         *     * `ram` - Memory
         *     * `gpu` - Graphics card
         *     * `storage` - Storage
         *     * `psu` - Power supply
         *     * `case` - Case
         *     * `cooler` - CPU cooler
         * @enum {string}
         */
        CategoryKindEnum: "cpu" | "motherboard" | "ram" | "gpu" | "storage" | "psu" | "case" | "cooler";
        CategoryRequest: {
            kind: components["schemas"]["CategoryKindEnum"];
            name: string;
            slug: string;
            position?: number;
        };
        CategoryStats: {
            kind: string;
            name: string;
            components: number;
            /** Format: decimal */
            avg_price: string;
            /** Format: decimal */
            min_price: string;
            /** Format: decimal */
            max_price: string;
        };
        Comment: {
            readonly id: number;
            readonly build: number;
            readonly author: string;
            text: string;
            /** Format: date-time */
            readonly created_at: string;
        };
        CommentRequest: {
            text: string;
        };
        /** @description Input of the stateless ``POST /compatibility/check/`` endpoint. */
        CompatibilityCheckRequest: {
            items: components["schemas"]["BuildItemWriteRequest"][];
        };
        CompatibilityReport: {
            is_compatible: boolean;
            is_complete: boolean;
            errors: components["schemas"]["Issue"][];
            warnings: components["schemas"]["Issue"][];
            missing: string[];
            estimated_wattage: number;
            recommended_psu_wattage: number;
        };
        Component: {
            readonly id: number;
            name: string;
            slug: string;
            sku: string;
            /**
             * Format: decimal
             * @description Price in USD
             */
            price: string;
            /** Format: decimal */
            readonly price_uah: string | null;
            specs: {
                [key: string]: unknown;
            };
            readonly specs_complete: boolean;
            readonly missing_specs: string[];
            /** @description Interest index from the source (hotline.ua), 7-day average. */
            readonly popularity: number | null;
            /** @description 1 = most popular in its category. */
            readonly popularity_rank: number | null;
            /** @description Shops selling it now (best listing); null = no market data. */
            readonly shop_count: number | null;
            /** @description False when fewer than MARKET_MIN_SHOPS shops sell it (hidden from the catalog). */
            readonly listed: boolean;
            /**
             * Format: decimal
             * @description Change of the average market price over 30 days, %.
             */
            readonly price_change_30d: string | null;
            /** @description Price is at its lowest of the last 12 months. */
            readonly at_year_low: boolean;
            readonly image: string | null;
            readonly images: string[];
            readonly market: components["schemas"]["Market"] | null;
            is_active?: boolean;
            readonly category: components["schemas"]["Category"];
            readonly manufacturer: components["schemas"]["Manufacturer"];
            /** Format: date-time */
            readonly updated_at: string;
        };
        /** @description Compact representation used inside builds and orders. */
        ComponentBrief: {
            readonly id: number;
            name: string;
            slug: string;
            readonly kind: components["schemas"]["CategoryKindEnum"];
            readonly manufacturer: string;
            /**
             * Format: decimal
             * @description Price in USD
             */
            price: string;
            readonly specs: {
                [key: string]: unknown;
            };
            readonly image: string | null;
            readonly market: components["schemas"]["Market"] | null;
            is_active?: boolean;
        };
        ComponentRequest: {
            name: string;
            slug: string;
            sku: string;
            /**
             * Format: decimal
             * @description Price in USD
             */
            price: string;
            specs: {
                [key: string]: unknown;
            };
            is_active?: boolean;
            category_id: number;
            manufacturer_id: number;
        };
        /**
         * @description * `USD` - USD
         *     * `UAH` - UAH
         * @enum {string}
         */
        CurrencyEnum: "USD" | "UAH";
        ExchangeRate: {
            currency: string;
            /** Format: decimal */
            rate: string;
            /** Format: date */
            rate_date: string;
            /** Format: date-time */
            readonly fetched_at: string;
        };
        Issue: {
            code: string;
            severity: components["schemas"]["SeverityEnum"];
            message: string;
            component_ids: number[];
            /** @description Values for rendering a localised message by `code`. */
            params: {
                [key: string]: unknown;
            };
        };
        /** @description Live market data of the component's primary listing. */
        Listing: {
            readonly id: number;
            /** @description Product name on the source */
            title?: string;
            images?: unknown;
            last_error?: string;
            /** @description Host name, e.g. hotline.ua */
            source: string;
            /** Format: uri */
            url: string;
            /** Format: decimal */
            low_price?: string | null;
            /** Format: decimal */
            high_price?: string | null;
            /** Format: decimal */
            median_price?: string | null;
            currency?: string;
            offer_count?: number | null;
            in_stock?: boolean | null;
            /** Format: decimal */
            rating?: string | null;
            review_count?: number | null;
            status?: components["schemas"]["ListingStatusEnum"];
            /** Format: date-time */
            checked_at?: string | null;
        };
        ListingCreateRequest: {
            /** Format: uri */
            url: string;
        };
        /**
         * @description * `pending` - Not checked yet
         *     * `ok` - Up to date
         *     * `no_offers` - No offers on the page
         *     * `mismatch` - Page shows a different product
         *     * `error` - Fetch failed
         * @enum {string}
         */
        ListingStatusEnum: "pending" | "ok" | "no_offers" | "mismatch" | "error";
        Manufacturer: {
            readonly id: number;
            name: string;
            slug: string;
            website?: string;
        };
        ManufacturerRequest: {
            name: string;
            slug: string;
            website?: string;
        };
        /** @description Live market data of the component's primary listing. */
        Market: {
            /** @description Host name, e.g. hotline.ua */
            source: string;
            /** Format: uri */
            url: string;
            /** Format: decimal */
            low_price?: string | null;
            /** Format: decimal */
            high_price?: string | null;
            /** Format: decimal */
            median_price?: string | null;
            currency?: string;
            offer_count?: number | null;
            in_stock?: boolean | null;
            /** Format: decimal */
            rating?: string | null;
            review_count?: number | null;
            status?: components["schemas"]["ListingStatusEnum"];
            /** Format: date-time */
            checked_at?: string | null;
        };
        Order: {
            readonly id: number;
            build?: number | null;
            status?: components["schemas"]["OrderStatusEnum"];
            /** Format: decimal */
            total: string;
            shipping_address: string;
            payment_provider?: string;
            readonly items: components["schemas"]["OrderItem"][];
            readonly allowed_transitions: string[];
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            /** Format: date-time */
            paid_at?: string | null;
        };
        OrderCreateRequest: {
            build: number;
            shipping_address: string;
        };
        OrderItem: {
            readonly id: number;
            component: number;
            component_name: string;
            /** Format: decimal */
            unit_price: string;
            quantity: number;
            /** Format: decimal */
            readonly line_total: string;
        };
        /**
         * @description * `pending` - Awaiting payment
         *     * `paid` - Paid
         *     * `shipped` - Shipped
         *     * `delivered` - Delivered
         *     * `cancelled` - Cancelled
         * @enum {string}
         */
        OrderStatusEnum: "pending" | "paid" | "shipped" | "delivered" | "cancelled";
        PaginatedBuildListList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["BuildList"][];
        };
        PaginatedComponentList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Component"][];
        };
        PaginatedExchangeRateList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["ExchangeRate"][];
        };
        PaginatedOrderList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Order"][];
        };
        /**
         * @description Create/update a build together with its component list.
         *
         *     Validation is layered on purpose:
         *     * field level  – each item references an active component, quantity 1..8;
         *     * ``validate_items`` – no duplicate components in one request;
         *     * ``validate`` – cross-field domain rules via the compatibility engine.
         *       This is the place for them: they depend on *all* items at once, which
         *       no single field validator can see;
         *     * database – unique (build, component) and the quantity range are also
         *       constraints, so a bug in this serializer cannot corrupt data.
         */
        PatchedBuildWriteRequest: {
            name?: string;
            description?: string;
            is_public?: boolean;
            items?: components["schemas"]["BuildItemWriteRequest"][];
        };
        PatchedCommentRequest: {
            text?: string;
        };
        PatchedComponentRequest: {
            name?: string;
            slug?: string;
            sku?: string;
            /**
             * Format: decimal
             * @description Price in USD
             */
            price?: string;
            specs?: {
                [key: string]: unknown;
            };
            is_active?: boolean;
            category_id?: number;
            manufacturer_id?: number;
        };
        PatchedTelegramStatusRequest: {
            /** @description Send price alerts. */
            enabled?: boolean;
            /** @description Hold alerts between 22:00 and 08:00 (Kyiv time). */
            quiet_hours?: boolean;
            language?: components["schemas"]["AlertLanguageEnum"];
        };
        PatchedUserRequest: {
            /** Email address */
            email?: string;
            first_name?: string;
            last_name?: string;
        };
        PatchedWatchRequest: {
            component?: number | null;
            build?: number | null;
            /**
             * Format: decimal
             * @description USD. Alert once the price reaches it (optional).
             */
            target_price?: string | null;
            /** @description Alert when the price moves this much, either way. */
            threshold_percent?: number;
        };
        PaymentSession: {
            provider: string;
            /** Format: uri */
            checkout_url: string | null;
            confirmed: boolean;
            order: components["schemas"]["Order"];
        };
        PopularComponent: {
            id: number;
            name: string;
            slug: string;
            kind: string;
            manufacturer: string;
            /** Format: decimal */
            price: string;
            build_count: number;
            rank?: number;
        };
        PriceHistory: {
            /** Format: decimal */
            price: string;
            /** Format: decimal */
            low_price?: string | null;
            /** Format: decimal */
            high_price?: string | null;
            source?: string;
            /** Format: date-time */
            recorded_at?: string;
        };
        PricePosition: {
            id: number;
            name: string;
            /** Format: decimal */
            price: string;
            price_rank: number;
            /** Format: double */
            percentile: number;
        };
        Register: {
            readonly id: number;
            /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
            username: string;
            /** Email address */
            email: string;
        };
        RegisterRequest: {
            /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
            username: string;
            /** Email address */
            email: string;
            password: string;
        };
        /**
         * @description * `error` - error
         *     * `warning` - warning
         * @enum {string}
         */
        SeverityEnum: "error" | "warning";
        /**
         * @description * `claude` - claude
         *     * `rule_based` - rule_based
         * @enum {string}
         */
        SourceEnum: "claude" | "rule_based";
        StatusChangeRequest: {
            status: components["schemas"]["OrderStatusEnum"];
        };
        TelegramLinkRequestRequest: {
            /** @default uk */
            language: components["schemas"]["AlertLanguageEnum"];
        };
        TelegramLinkResponse: {
            /**
             * Format: uri
             * @description Open it: Telegram starts the bot with a one-time code.
             */
            url: string;
            /** @description Seconds. */
            expires_in: number;
        };
        TelegramStatus: {
            readonly linked: boolean;
            readonly username: string;
            /** @description Send price alerts. */
            enabled?: boolean;
            /** @description Hold alerts between 22:00 and 08:00 (Kyiv time). */
            quiet_hours?: boolean;
            language?: components["schemas"]["AlertLanguageEnum"];
            /** Format: date-time */
            readonly linked_at: string | null;
            readonly bot_username: string | null;
            /** Format: uri */
            readonly bot_url: string | null;
        };
        TokenObtainPair: {
            readonly access: string;
            readonly refresh: string;
        };
        TokenObtainPairRequest: {
            username: string;
            password: string;
        };
        TokenRefresh: {
            readonly access: string;
            refresh: string;
        };
        TokenRefreshRequest: {
            refresh: string;
        };
        /**
         * @description * `gaming` - gaming
         *     * `workstation` - workstation
         *     * `streaming` - streaming
         *     * `office` - office
         * @enum {string}
         */
        UseCaseEnum: "gaming" | "workstation" | "streaming" | "office";
        User: {
            readonly id: number;
            /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
            readonly username: string;
            /** Email address */
            email?: string;
            first_name?: string;
            last_name?: string;
            /**
             * Staff status
             * @description Designates whether the user can log into this admin site.
             */
            readonly is_staff: boolean;
            /** Format: date-time */
            readonly date_joined: string;
        };
        UserRequest: {
            /** Email address */
            email?: string;
            first_name?: string;
            last_name?: string;
        };
        Watch: {
            readonly id: number;
            component?: number | null;
            build?: number | null;
            readonly item: components["schemas"]["WatchItem"];
            /**
             * Format: decimal
             * @description USD. Alert once the price reaches it (optional).
             */
            target_price?: string | null;
            /** @description Alert when the price moves this much, either way. */
            threshold_percent?: number;
            /**
             * Format: decimal
             * @description USD. Price when the watch was created or last alerted; changes count from it.
             */
            readonly baseline_price: string;
            /** Format: decimal */
            readonly current_price: string | null;
            /** Format: decimal */
            readonly change_percent: string | null;
            /** Format: date-time */
            readonly last_notified_at: string | null;
            /** Format: date-time */
            readonly created_at: string;
        };
        /** @description What a watch points at, flattened for lists (profile page, bot). */
        WatchItem: {
            kind: components["schemas"]["WatchItemKindEnum"];
            name: string;
            /** @description Site path, e.g. /catalog/<slug> or /builds/<id>. */
            path: string;
            image: string | null;
            category: string | null;
        };
        /**
         * @description * `component` - component
         *     * `build` - build
         * @enum {string}
         */
        WatchItemKindEnum: "component" | "build";
        WatchRequest: {
            component?: number | null;
            build?: number | null;
            /**
             * Format: decimal
             * @description USD. Alert once the price reaches it (optional).
             */
            target_price?: string | null;
            /** @description Alert when the price moves this much, either way. */
            threshold_percent?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    advisor_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdvisorRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["AdvisorRequest"];
                "multipart/form-data": components["schemas"]["AdvisorRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdvisorResponse"];
                };
            };
        };
    };
    auth_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    auth_me_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UserRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["UserRequest"];
                "multipart/form-data": components["schemas"]["UserRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    auth_me_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedUserRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedUserRequest"];
                "multipart/form-data": components["schemas"]["PatchedUserRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    auth_register_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["RegisterRequest"];
                "multipart/form-data": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Register"];
                };
            };
        };
    };
    auth_token_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenObtainPairRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenObtainPairRequest"];
                "multipart/form-data": components["schemas"]["TokenObtainPairRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenObtainPair"];
                };
            };
        };
    };
    auth_token_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefreshRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenRefreshRequest"];
                "multipart/form-data": components["schemas"]["TokenRefreshRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefresh"];
                };
            };
        };
    };
    builds_list: {
        parameters: {
            query?: {
                /** @description Only builds that contain this component id. */
                component?: number;
                is_public?: boolean;
                max_total?: number;
                min_total?: number;
                mine?: boolean;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                owner?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedBuildListList"];
                };
            };
        };
    };
    builds_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BuildWriteRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["BuildWriteRequest"];
                "multipart/form-data": components["schemas"]["BuildWriteRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildDetail"];
                };
            };
        };
    };
    builds_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this build. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildDetail"];
                };
            };
        };
    };
    builds_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this build. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BuildWriteRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["BuildWriteRequest"];
                "multipart/form-data": components["schemas"]["BuildWriteRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildDetail"];
                };
            };
        };
    };
    builds_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this build. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    builds_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this build. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedBuildWriteRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedBuildWriteRequest"];
                "multipart/form-data": components["schemas"]["PatchedBuildWriteRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildDetail"];
                };
            };
        };
    };
    builds_clone_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this build. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildDetail"];
                };
            };
        };
    };
    builds_comments_list: {
        parameters: {
            query?: {
                /** @description Only builds that contain this component id. */
                component?: number;
                is_public?: boolean;
                max_total?: number;
                min_total?: number;
                mine?: boolean;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                owner?: string;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path: {
                /** @description A unique integer value identifying this build. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comment"][];
                };
            };
        };
    };
    builds_comments_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this build. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommentRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CommentRequest"];
                "multipart/form-data": components["schemas"]["CommentRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comment"];
                };
            };
        };
    };
    builds_compatibility_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this build. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompatibilityReport"];
                };
            };
        };
    };
    categories_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"][];
                };
            };
        };
    };
    categories_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
        };
    };
    comments_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this comment. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comment"];
                };
            };
        };
    };
    comments_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this comment. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommentRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CommentRequest"];
                "multipart/form-data": components["schemas"]["CommentRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comment"];
                };
            };
        };
    };
    comments_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this comment. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    comments_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this comment. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedCommentRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedCommentRequest"];
                "multipart/form-data": components["schemas"]["PatchedCommentRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comment"];
                };
            };
        };
    };
    compatibility_check_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompatibilityCheckRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CompatibilityCheckRequest"];
                "multipart/form-data": components["schemas"]["CompatibilityCheckRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompatibilityReport"];
                };
            };
        };
    };
    components_list: {
        parameters: {
            query?: {
                /** @description Only parts with complete specs (usable in the configurator). */
                buildable?: boolean;
                /**
                 * @description * `cpu` - Processor
                 *     * `motherboard` - Motherboard
                 *     * `ram` - Memory
                 *     * `gpu` - Graphics card
                 *     * `storage` - Storage
                 *     * `psu` - Power supply
                 *     * `case` - Case
                 *     * `cooler` - CPU cooler
                 */
                category?: "case" | "cooler" | "cpu" | "gpu" | "motherboard" | "psu" | "ram" | "storage";
                /** @description Comma-separated ids of already selected components. Only parts compatible with them are returned. Requires `category`. */
                compatible_with?: string;
                form_factor?: string;
                is_active?: boolean;
                manufacturer?: string;
                max_price?: number;
                memory_type?: string;
                min_price?: number;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description A search term. */
                search?: string;
                socket?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedComponentList"];
                };
            };
        };
    };
    components_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComponentRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ComponentRequest"];
                "multipart/form-data": components["schemas"]["ComponentRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Component"];
                };
            };
        };
    };
    components_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Component"];
                };
            };
        };
    };
    components_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComponentRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ComponentRequest"];
                "multipart/form-data": components["schemas"]["ComponentRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Component"];
                };
            };
        };
    };
    components_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    components_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedComponentRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedComponentRequest"];
                "multipart/form-data": components["schemas"]["PatchedComponentRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Component"];
                };
            };
        };
    };
    components_listings_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ListingCreateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ListingCreateRequest"];
                "multipart/form-data": components["schemas"]["ListingCreateRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Listing"];
                };
            };
        };
    };
    components_price_history_list: {
        parameters: {
            query?: {
                /** @description Only parts with complete specs (usable in the configurator). */
                buildable?: boolean;
                /**
                 * @description * `cpu` - Processor
                 *     * `motherboard` - Motherboard
                 *     * `ram` - Memory
                 *     * `gpu` - Graphics card
                 *     * `storage` - Storage
                 *     * `psu` - Power supply
                 *     * `case` - Case
                 *     * `cooler` - CPU cooler
                 */
                category?: "case" | "cooler" | "cpu" | "gpu" | "motherboard" | "psu" | "ram" | "storage";
                /** @description Comma-separated component ids; requires `category`. */
                compatible_with?: string;
                /** @description Only the last N days (e.g. 30, 90, 180, 365). Default: everything. */
                days?: number;
                form_factor?: string;
                is_active?: boolean;
                manufacturer?: string;
                max_price?: number;
                memory_type?: string;
                min_price?: number;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A search term. */
                search?: string;
                socket?: string;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceHistory"][];
                };
            };
        };
    };
    exchange_rates_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedExchangeRateList"];
                };
            };
        };
    };
    exchange_rates_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this exchange rate. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExchangeRate"];
                };
            };
        };
    };
    exchange_rates_latest_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExchangeRate"];
                };
            };
        };
    };
    manufacturers_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Manufacturer"][];
                };
            };
        };
    };
    manufacturers_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Manufacturer"];
                };
            };
        };
    };
    orders_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description A search term. */
                search?: string;
                /**
                 * @description * `pending` - Awaiting payment
                 *     * `paid` - Paid
                 *     * `shipped` - Shipped
                 *     * `delivered` - Delivered
                 *     * `cancelled` - Cancelled
                 */
                status?: "cancelled" | "delivered" | "paid" | "pending" | "shipped";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedOrderList"];
                };
            };
        };
    };
    orders_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderCreateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["OrderCreateRequest"];
                "multipart/form-data": components["schemas"]["OrderCreateRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
        };
    };
    orders_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this order. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
        };
    };
    orders_advance_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this order. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusChangeRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["StatusChangeRequest"];
                "multipart/form-data": components["schemas"]["StatusChangeRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
        };
    };
    orders_cancel_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this order. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
        };
    };
    orders_pay_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this order. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentSession"];
                };
            };
        };
    };
    stats_categories_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryStats"][];
                };
            };
        };
    };
    stats_cheapest_build_retrieve: {
        parameters: {
            query: {
                gpu: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildList"];
                };
            };
            /** @description No response body */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    stats_popular_components_list: {
        parameters: {
            query?: {
                /** @description Default 10, max 50 */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PopularComponent"][];
                };
            };
        };
    };
    stats_price_position_list: {
        parameters: {
            query: {
                category: "case" | "cooler" | "cpu" | "gpu" | "motherboard" | "psu" | "ram" | "storage";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PricePosition"][];
                };
            };
        };
    };
    stats_top_per_category_list: {
        parameters: {
            query?: {
                /** @description Default 3, max 10 */
                top?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PopularComponent"][];
                };
            };
        };
    };
    telegram_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelegramStatus"];
                };
            };
        };
    };
    telegram_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    telegram_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedTelegramStatusRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedTelegramStatusRequest"];
                "multipart/form-data": components["schemas"]["PatchedTelegramStatusRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelegramStatus"];
                };
            };
        };
    };
    telegram_link_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["TelegramLinkRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TelegramLinkRequestRequest"];
                "multipart/form-data": components["schemas"]["TelegramLinkRequestRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelegramLinkResponse"];
                };
            };
        };
    };
    watches_list: {
        parameters: {
            query?: {
                /** @description Only this build. */
                build?: number;
                /** @description Only this part. */
                component?: number;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Watch"][];
                };
            };
        };
    };
    watches_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["WatchRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["WatchRequest"];
                "multipart/form-data": components["schemas"]["WatchRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Watch"];
                };
            };
        };
    };
    watches_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this watch. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Watch"];
                };
            };
        };
    };
    watches_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this watch. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    watches_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this watch. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedWatchRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedWatchRequest"];
                "multipart/form-data": components["schemas"]["PatchedWatchRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Watch"];
                };
            };
        };
    };
}
