# Generated by Django 5.2.17 on 2026-09-23 16:13

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('cpu', 'Processor'), ('motherboard', 'Motherboard'), ('ram', 'Memory'), ('gpu', 'Graphics card'), ('storage', 'Storage'), ('psu', 'Power supply'), ('case', 'Case'), ('cooler', 'CPU cooler')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(unique=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('website', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=12)),
                ('rate_date', models.DateField()),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-rate_date'],
                'constraints': [models.UniqueConstraint(fields=('currency', 'rate_date'), name='unique_rate_per_day'), models.CheckConstraint(condition=models.Q(('rate__gt', 0)), name='exchange_rate_positive')],
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('sku', models.CharField(max_length=64, unique=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in USD', max_digits=10)),
                ('specs', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='components', to='catalog.category')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='components', to='catalog.manufacturer')),
            ],
            options={
                'ordering': ['category__position', 'price'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('source', models.CharField(default='feed', max_length=32)),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='catalog.component')),
            ],
            options={
                'verbose_name_plural': 'price history',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='component',
            index=django.contrib.postgres.indexes.GinIndex(fields=['specs'], name='component_specs_gin', opclasses=['jsonb_path_ops']),
        ),
        migrations.AddIndex(
            model_name='component',
            index=models.Index(fields=['category', 'price'], name='component_category_price_idx'),
        ),
        migrations.AddConstraint(
            model_name='component',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='component_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='component',
            constraint=models.UniqueConstraint(fields=('manufacturer', 'name'), name='component_unique_name_per_manufacturer'),
        ),
    ]
