# Generated by Django 5.2.17 on 2026-09-23 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, unique=True)),
                ('source', models.CharField(help_text='Host name, e.g. hotline.ua', max_length=64)),
                ('title', models.CharField(blank=True, help_text='Product name on the source', max_length=300)),
                ('low_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('high_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('offer_count', models.PositiveIntegerField(blank=True, null=True)),
                ('in_stock', models.BooleanField(null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('review_count', models.PositiveIntegerField(blank=True, null=True)),
                ('images', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Not checked yet'), ('ok', 'Up to date'), ('no_offers', 'No offers on the page'), ('mismatch', 'Page shows a different product'), ('error', 'Fetch failed')], db_index=True, default='pending', max_length=16)),
                ('last_error', models.CharField(blank=True, max_length=500)),
                ('checked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='catalog.component')),
            ],
            options={
                'ordering': ['component_id', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('low_price__isnull', True), ('high_price__isnull', True), ('low_price__lte', models.F('high_price')), _connector='OR'), name='listing_low_le_high'), models.CheckConstraint(condition=models.Q(('low_price__isnull', True), ('low_price__gte', 0), _connector='OR'), name='listing_price_non_negative')],
            },
        ),
    ]
