# Generated by Django 5.2.17 on 2026-09-23 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_market_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='specs_complete',
            field=models.BooleanField(db_index=True, default=True, editable=False),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(max_length=500)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('thumb', models.ImageField(upload_to='products/thumbs/')),
                ('large', models.ImageField(upload_to='products/large/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='catalog.component')),
            ],
            options={
                'ordering': ['component_id', 'position'],
                'constraints': [models.UniqueConstraint(fields=('component', 'source_url'), name='product_image_unique_source')],
            },
        ),
    ]
