# Generated by Django 5.2.17 on 2026-09-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_market_median_and_daily_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='at_year_low',
            field=models.BooleanField(default=False, editable=False, help_text='Price is at its lowest of the last 12 months.'),
        ),
        migrations.AddField(
            model_name='component',
            name='popularity',
            field=models.PositiveIntegerField(blank=True, db_index=True, editable=False, help_text='Interest index from the source (hotline.ua), 7-day average.', null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='popularity_rank',
            field=models.PositiveIntegerField(blank=True, editable=False, help_text='1 = most popular in its category.', null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='price_change_30d',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=1, editable=False, help_text='Change of the average market price over 30 days, %.', max_digits=6, null=True),
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['component', 'recorded_at'], name='pricehistory_comp_time_idx'),
        ),
    ]
