# Generated by Django 5.2.17 on 2026-09-24 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_market_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='shop_count',
            field=models.PositiveIntegerField(blank=True, db_index=True, editable=False, help_text='Shops selling it now (best listing); null = no market data.', null=True),
        ),
    ]
