# Generated by Django 5.2.17 on 2026-09-23 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='BuildComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_components', to='builds.build')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='build_components', to='catalog.component')),
            ],
        ),
        migrations.AddField(
            model_name='build',
            name='components',
            field=models.ManyToManyField(related_name='builds', through='builds.BuildComponent', to='catalog.component'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='builds.build')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='buildcomponent',
            constraint=models.UniqueConstraint(fields=('build', 'component'), name='build_component_unique'),
        ),
        migrations.AddConstraint(
            model_name='buildcomponent',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1), ('quantity__lte', 8)), name='build_component_quantity_range'),
        ),
        migrations.AddConstraint(
            model_name='build',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='build_unique_name_per_owner'),
        ),
    ]
